### ISSUE TITLE
Normalizing Vector

### ISSUE THREAD

**Issue by KROIA** [twobitcoder101/FlatPhysics#1]
Hi, as you might have seen in my youtube comment, I think here is an issue.

Your code:
https://github.com/twobitcoder101/FlatPhysics/blob/cd3ecd01678887e2a88606900e31c76fde927b80/Collisions.cs#L122-L191

My variant:
```cs
public static bool IntersectPolygons(FlatVector[] verticesA, FlatVector[] verticesB, out FlatVector normal, out float depth)
{
    normal = FlatVector.Zero;
    depth = float.MaxValue;

    for(int i = 0; i < verticesA.Length; i++)
    {
        FlatVector va = verticesA[i];
        FlatVector vb = verticesA[(i + 1) % verticesA.Length];

        FlatVector edge = vb - va;
        FlatVector axis = new FlatVector(-edge.Y, edge.X);
		
	// Normalize the vector, so the min/max Values have the same scaling factor
        //and therefore you can compare them with them of other axis.
	axis  = FlatMath.Normalize(axis);

        Collisions.ProjectVertices(verticesA, axis, out float minA, out float maxA);
        Collisions.ProjectVertices(verticesB, axis, out float minB, out float maxB);

        if(minA >= maxB || minB >= maxA)
        {
            return false;
        }

        float axisDepth = MathF.Min(maxB - minA, maxA - minB);

        if(axisDepth < depth)
        {
            depth = axisDepth;
            normal = axis;
        }
    }

    for (int i = 0; i < verticesB.Length; i++)
    {
        FlatVector va = verticesB[i];
        FlatVector vb = verticesB[(i + 1) % verticesB.Length];

        FlatVector edge = vb - va;
        FlatVector axis = new FlatVector(-edge.Y, edge.X);

        // Normalize the vector, so the min/max Values have the same scaling factor
        //and therefore you can compare them with them of other axis.
	axis  = FlatMath.Normalize(axis);

        Collisions.ProjectVertices(verticesA, axis, out float minA, out float maxA);
        Collisions.ProjectVertices(verticesB, axis, out float minB, out float maxB);

        if (minA >= maxB || minB >= maxA)
        {
            return false;
        }

        float axisDepth = MathF.Min(maxB - minA, maxA - minB);

        if (axisDepth < depth)
        {
            depth = axisDepth;
            normal = axis;
        }
    }

    // Because the axis vector is normalized, the depth and normal are also normalized
    //depth /= FlatMath.Length(normal);
    //normal = FlatMath.Normalize(normal);

    FlatVector centerA = Collisions.FindArithmeticMean(verticesA);
    FlatVector centerB = Collisions.FindArithmeticMean(verticesB);

    FlatVector direction = centerB - centerA;

    if(FlatMath.Dot(direction, normal) < 0f)
    {
        normal = -normal;
    }

    return true;
}
```

**Comment by twobitcoder101** [comment]
Interesting.. I haven’t seen a problem doing the normalization after the loops..  I will have to look into that.. All the collisions seems to resolve correctly, but I do think I understand what you are sayin. When comparing to the other axis in the next iteration of the loop it is a different scale? I will run through some tests and make the correction if necessary. -thanks. From: Alex KriegSent: Sunday, July 25, 2021 1:09 PMTo: twobitcoder101/FlatPhysicsCc: SubscribedSubject: [twobitcoder101/FlatPhysics] Normalizing Vector (#1) Hi, as you might have seen in my youtube comment, I think here is an issue.Your code:https://github.com/twobitcoder101/FlatPhysics/blob/cd3ecd01678887e2a88606900e31c76fde927b80/Collisions.cs#L122-L191My variant:public static bool IntersectPolygons(FlatVector[] verticesA, FlatVector[] verticesB, out FlatVector normal, out float depth){    normal = FlatVector.Zero;    depth = float.MaxValue;     for(int i = 0; i < verticesA.Length; i++)    {        FlatVector va = verticesA[i];        FlatVector vb = verticesA[(i + 1) % verticesA.Length];         FlatVector edge = vb - va;        FlatVector axis = new FlatVector(-edge.Y, edge.X);                       // Normalize the vector, so the min/max Values have the same scaling factor        //and therefore you can compare them with them of other axis.        axis  = FlatMath.Normalize(axis);         Collisions.ProjectVertices(verticesA, axis, out float minA, out float maxA);        Collisions.ProjectVertices(verticesB, axis, out float minB, out float maxB);         if(minA >= maxB || minB >= maxA)        {            return false;        }         float axisDepth = MathF.Min(maxB - minA, maxA - minB);         if(axisDepth < depth)        {            depth = axisDepth;            normal = axis;        }    }     for (int i = 0; i < verticesB.Length; i++)    {        FlatVector va = verticesB[i];        FlatVector vb = verticesB[(i + 1) % verticesB.Length];         FlatVector edge = vb - va;        FlatVector axis = new FlatVector(-edge.Y, edge.X);         // Normalize the vector, so the min/max Values have the same scaling factor        //and therefore you can compare them with them of other axis.        axis  = FlatMath.Normalize(axis);         Collisions.ProjectVertices(verticesA, axis, out float minA, out float maxA);        Collisions.ProjectVertices(verticesB, axis, out float minB, out float maxB);         if (minA >= maxB || minB >= maxA)        {            return false;        }         float axisDepth = MathF.Min(maxB - minA, maxA - minB);         if (axisDepth < depth)        {            depth = axisDepth;            normal = axis;        }    }     // Because the axis vector is normalized, the depth and normal are also normalized    //depth /= FlatMath.Length(normal);    //normal = FlatMath.Normalize(normal);     FlatVector centerA = Collisions.FindArithmeticMean(verticesA);    FlatVector centerB = Collisions.FindArithmeticMean(verticesB);     FlatVector direction = centerB - centerA;     if(FlatMath.Dot(direction, normal) < 0f)    {        normal = -normal;    }     return true;}—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by KROIA** [comment]
" When comparing to the other axis in the next iteration of the loop it is a different scale?"
Exactly, because they depend on each edge and every edge may has a different length.
I saw the problem occuring when i tested a dynamic object colliding witz 2 static objects which vreated a corner, line in a room when something hits zwo walls in the corner. So.etimes the dynamic object gliched thro the walls.
I then deactivated the solving of the collision and yust displaid the solving vectors. Then i saw that, when one object has a very short edge vompared to the other edges, the min depth becoms also very low. But that's not true, because of the scaling, the other depth would be smaller. Because of that, the resolving vector will no longer perpendicular to the large edge and therefore the resolving would not take the shortest vector.
I hope my explanation is helpfull 😅

**Comment by twobitcoder101** [comment]
Yes. I didn’t see it at first. Thanks for the help!   From: Alex KriegSent: Monday, July 26, 2021 12:22 AMTo: twobitcoder101/FlatPhysicsCc: twobitcoder101; CommentSubject: Re: [twobitcoder101/FlatPhysics] Normalizing Vector (#1) " When comparing to the other axis in the next iteration of the loop it is a different scale?"Exactly, because they depend on each edge and every edge may has a different length.I saw the problem occuring when i tested a dynamic object colliding witz 2 static objects which vreated a corner, line in a room when something hits zwo walls in the corner. So.etimes the dynamic object gliched thro the walls.I then deactivated the solving of the collision and yust displaid the solving vectors. Then i saw that, when one object has a very short edge vompared to the other edges, the min depth becoms also very low. But that's not true, because of the scaling, the other depth would be smaller. Because of that, the resolving vector will no longer perpendicular to the large edge and therefore the resolving would not take the shortest vector.I hope my explanation is helpfull 😅—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
